### ISSUE TITLE
Metrics plugin is not configured properly

### ISSUE THREAD

**Issue by borcsokj** [arkmq-org/arkmq-org-broker-init-image#27]
**Describe the bug**
ArtemisPrometheusMetricsPlugin is added to broker.xml but artifacts (JAR, WAR) are missing from classpath and `bootstrap.xml` contains no metrics entry if `AMQ_ENABLE_METRICS_PLUGIN=true` (set by *enableMetricsPlugin*,  [operator PR](https://github.com/artemiscloud/activemq-artemis-operator/pull/92) ).

**To Reproduce**
1. Install ActiveMQ Artemis by Kubernetes operator and set *enableMetricsPlugin* to `true`
2. Broker fails to start because of ClassNotFoundException and bootstrap.xml has missing configuration (app).

**Platform (please complete the following information):**
 - ActiveMQ Artemis operator: 1.0.6
 - Broker init image: 1.0.9

**Expected behavior**
Metrics plugins have to be copied to target directories (JAR: `${CONFIG_INSTANCE_DIR}/lib`, WAR: `${CONFIG_INSTANCE_DIR}/web`) and bootstrap XML have to be extended by metrics app as described in https://github.com/artemiscloud/activemq-artemis-operator/issues/62 (and https://github.com/rh-messaging/artemis-prometheus-metrics-plugin).

**Comment by borcsokj** [comment]
**Workaround**

Define custom `post-config.sh` script (https://github.com/artemiscloud/activemq-artemis-broker-init-image/pull/26) and copy required files from extraMount path (already supported by operator) to target location:

broker.yaml (for Kubernetes operator):
```
apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: artemis-broker
spec:
  deploymentPlan:
    extraMounts:
      configMaps:
        - broker-configuration
        - broker-metrics-plugin
  env:
    - name: CUSTOM_CFG
      value: /amq/extra/configmaps/broker-configuration/post-config.sh
```

Installing `metrics-plugin.jar` and `metrics-plugin-servlet.jar` files from directory `./metrics-plugin/`:
```
kubectl create configmap broker-metrics-plugin --from-file=./metrics-plugin/
```


broker-configuration.yaml (containing `post-config.sh`)
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: broker-configuration
data:
  post-config.sh: |
    #!/bin/bash
    
    # Setup Prometheus plugins for metrics
    mkdir -p ${CONFIG_INSTANCE_DIR}/lib/
    mkdir -p ${CONFIG_INSTANCE_DIR}/web/
    cp /amq/extra/configmaps/broker-metrics-plugin/metrics-plugin.jar ${CONFIG_INSTANCE_DIR}/lib/
    cp /amq/extra/configmaps/broker-metrics-plugin/metrics-plugin-servlet.war ${CONFIG_INSTANCE_DIR}/web/
    sed s/"\(^\s*<\/binding\)"/"           \<app url=\"metrics\" war=\"metrics-plugin-servlet.war\"\/>\n\1"/ -i ${CONFIG_INSTANCE_DIR}/etc/bootstrap.xml
```

There is no need to build custom broker init image (if https://github.com/artemiscloud/activemq-artemis-broker-init-image/pull/26 is accepted) and plugin is installed from Kubernetes (offline).
