### ISSUE TITLE
consoleDomain.name in ActiveMQArtemisSecurity is not reflected in artemis.profile ( -Dhawtio.realm is not changed)

### ISSUE THREAD

**Issue by gaohoward** [arkmq-org/arkmq-org-broker-init-image#28]
**Describe the bug**
In ActiveMQArtemisSecurity under _spec.securityDomains_ add:
```
 consoleDomain:
      name: console
      loginModules:
        - name: prop-module
          flag: required
```
In the broker pod, in the configuration file _artemis.profile_, Dhawtio.realm is unchanged: 
-Dhawtio.realm=activemq

**To Reproduce**
1. Get X version of the source
2. '...'

**Platform (please complete the following information):**
 - OS: [e.g. Fedora]
 - Version [e.g. 32]
 - Container build tool [e.g. Podman]

**Expected behavior**
Optional, use if not obvious. A clear and concise description of what you expected to happen.

**Screenshots**
Optional, add screenshots to help explain your problem.

**Additional context**
Optional. Add any other context about the problem here.
