### ISSUE TITLE
The security CR's management.connector config is wrongly handled

### ISSUE THREAD

**Issue by gaohoward** [arkmq-org/arkmq-org-broker-init-image#37]
**Describe the bug**
When you deploy a security CR configuring connector it doesnt work.
example:
```
apiVersion: broker.amq.io/v1alpha1
kind: ActiveMQArtemisSecurity
metadata:
  name: demo-jmx
spec:
  applyToCrNames: 
  - demo
  securitySettings:
    management:
      connector:
        secured: false
```
The deployment will fail with init container error. The reason is that the connector's attributes are not correctly handled in the security apply script.

**To Reproduce**
1. Get X version of the source
2. '...'

**Platform (please complete the following information):**
 - OS: [e.g. Fedora]
 - Version [e.g. 32]
 - Container build tool [e.g. Podman]

**Expected behavior**
Optional, use if not obvious. A clear and concise description of what you expected to happen.

**Screenshots**
Optional, add screenshots to help explain your problem.

**Additional context**
Optional. Add any other context about the problem here.
