### ISSUE TITLE
Setting EnableIngressTimestamp causes invalid broker.xml

### ISSUE THREAD

**Issue by brusdev** [arkmq-org/arkmq-org-broker-init-image#50]
The yacfg tool included in quay.io/artemiscloud/activemq-artemis-broker-init:1.0.23 generates camel case values for the `enable-ingress-timestamp` element that are invalid xml boolean xml element values, i.e.

YAML:
```
user_address_settings:
- match: #
  dead_letter_address: dlqabc
  max_size_bytes: 10m
  redistribution_delay: 5000
  enable_ingress_timestamp: true
  max_size_messages: 5000
  config_delete_diverts: OFF
```
XML:
```
<address-setting match="#">
    <dead-letter-address>dlqabc</dead-letter-address>
    <redistribution-delay>5000</redistribution-delay>
    <max-size-bytes>10m</max-size-bytes>
    <enable-ingress-timestamp>True</enable-ingress-timestamp>
    <max-size-messages>5000</max-size-messages>
    <config-delete-diverts>OFF</config-delete-diverts>
</address-setting>
```
